version: '2'
services:
  rawgithack:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - cache:/var/cache/nginx/rawgithack:rw
      - /root/docker/rawgithack/config.lua:/etc/nginx/rawgithack/config.lua:rw
    ports:
      - "80:80"

volumes:
  cache:
